def poiEmails():
    email_list = {"LAY KENNETH L":["kenneth_lay@enron.net",    
            "kenneth_lay@enron.com",
            "klay.enron@enron.com",
            "kenneth.lay@enron.com", 
            "klay@enron.com",
            "layk@enron.com",
            "chairman.ken@enron.com"],
            "SKILLING JEFFREY K":["jeffreyskilling@yahoo.com",
            "jeff_skilling@enron.com",
            "jskilling@enron.com",
            "effrey.skilling@enron.com",
            "skilling@enron.com",
            "jeffrey.k.skilling@enron.com",
            "jeff.skilling@enron.com"],
            "HOWARD KEVIN":["kevin_a_howard.enronxgate.enron@enron.net",
            "kevin.howard@enron.com",
            "kevin.howard@enron.net",
            "kevin.howard@gcm.com"],
            "KRAUTZ MICHAEL":["michael.krautz@enron.com"],
            "YEAGER F SCOTT":["scott.yeager@enron.com",
            "syeager@fyi-net.com",
            "scott_yeager@enron.net",
            "syeager@flash.net"],
            "HIRKO JOSEPH":["joe'.'hirko@enron.com", 
            "joe.hirko@enron.com"], 
            "SHELBY REX":["rex.shelby@enron.com", 
            "rex.shelby@enron.nt", 
            "rex_shelby@enron.net"],
            "BROWN JAMES":["jbrown@enron.com",
            "james.brown@enron.com"], 
            "CAUSEY RICHARD A":["rick.causey@enron.com", 
            "richard.causey@enron.com", 
            "rcausey@enron.com"],
            "CALGER CHRISTOPHER F":["calger@enron.com",
            "chris.calger@enron.com", 
            "christopher.calger@enron.com", 
            "ccalger@enron.com"],
            "DESPAIN TIM":["tim_despain.enronxgate.enron@enron.net", 
            "tim.despain@enron.com"],
            "HANNON KEVIN P":["kevin_hannon@enron.com", 
            "kevin'.'hannon@enron.com", 
            "kevin_hannon@enron.net", 
            "kevin.hannon@enron.com"],
            "KOENIG MARK E":["mkoenig@enron.com", 
            "mark.koenig@enron.com"],
            "FORNEY M":["m..forney@enron.com"],
            "RICE KENNETH D":["ken'.'rice@enron.com", 
            "ken.rice@enron.com",
            "ken_rice@enron.com", 
            "ken_rice@enron.net"],
            "RIEKER PAULA H":["paula.rieker@enron.com",
            "prieker@enron.com"], 
            "FASTOW ANDREW S":["andrew.fastow@enron.com", 
            "lfastow@pdq.net", 
            "andrew.s.fastow@enron.com", 
            "lfastow@pop.pdq.net", 
            "andy.fastow@enron.com"],
            "DELAINEY DAVID W":["david.w.delainey@enron.com", 
            "delainey.dave@enron.com", 
            "'delainey@enron.com", 
            "david.delainey@enron.com", 
            "'david.delainey'@enron.com", 
            "dave.delainey@enron.com", 
            "delainey'.'david@enron.com"],
            "GLISAN JR BEN F":["ben.glisan@enron.com", 
            "bglisan@enron.com", 
            "ben_f_glisan@enron.com"],
            "RICHTER JEFF":["jeff.richter@enron.com", 
            "jrichter@nwlink.com"],
            "LAWYER LAWRENCE":["lawrencelawyer@aol.com", 
            "lawyer'.'larry@enron.com", 
            "larry_lawyer@enron.com", 
            "llawyer@enron.com", 
            "larry.lawyer@enron.com", 
            "lawrence.lawyer@enron.com"],
            "BELDEN TIMOTHY N":["tbelden@enron.com", 
            "tim.belden@enron.com", 
            "tim_belden@pgn.com", 
            "tbelden@ect.enron.com"],
			"KOPPER MICHAEL J":["michael.kopper@enron.com"],
            "DUNCAN DAVE":["dave.duncan@enron.com", 
            "dave.duncan@cipco.org", 
            "duncan.dave@enron.com"],
            "BOWEN JR RAYMOND M":["ray.bowen@enron.com", 
            "raymond.bowen@enron.com", 
            "'bowen@enron.com"],
            "COLWELL WESLEY":["wes.colwell@enron.com"],
            "BOYLE DAN":["dan.boyle@enron.com"],
            "LOEHR CHRIS":["cloehr@enron.com", 
            "chris.loehr@enron.com"]
        }
    return email_list
